services:
  api:
    container_name: sharkcare-server
    image: khizer30/sharkcare-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
